name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip esp32.zip

      - name: Find flutter project
        run: find . -name "pubspec.yaml" | head -5

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.1'
          channel: 'stable'

      - name: Get packages and Build
        run: |
          PROJECT=$(find . -name "pubspec.yaml" | head -1 | xargs dirname)
          echo "Found project at: $PROJECT"
          cd $PROJECT
          flutter pub get
          flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ESP32-Monitor-APK
          path: "**/app-debug.apk"
